### ISSUE TITLE
Second Spring setting

### ISSUE THREAD

**Issue by malexx74** [joeyjojojunior/simFFB#2]
Would it be possible to add a second spring strenght setting for the trimmer?

**Comment by joeyjojojunior** [comment]
Hey, I've been rather busy lately so sorry for the late reply. Should be a pretty simple addition. I'll try to work on it this weekend. I'm assuming you fixed the other issue you raised the other day about the debug thing? Out of curiosity, how did you find this repo?

**Comment by malexx74** [comment]
Hi,
Thank you for your answer :)

Yes I compiled myself.
Well I am one of those hardcore FFb users and was searching for anything related to customize FFb settings. I know SImmFFB and was using it.

I found your repo over a google search.
Really nice work and I am glad you made this, using it now for every flight.
I pronounced your repo in the German dcs forum, so maybe this is useful for others too.

If you could add settings for the second spring force, this would be amazing and pretty useful for the KA50 in dcs, so when constantly trimming there is some force on the stick.

Anyway, thank you for your work, appreciate it much.

Greets Alex



Am 11. März 2020, 00:27 +0100 schrieb joeyjojojunior <notifications@github.com>:

**Comment by joeyjojojunior** [comment]
Nice, glad you like it :)

I've just implemented the separate spring force. Let me know how it is. I also put the release binary up this time, so hopefully you won't have that debug issue.

**Comment by malexx74** [comment]
Hi,
That sound great, I will test it and report back.

Tank you very much!
Am 18. März 2020, 04:12 +0100 schrieb joeyjojojunior <notifications@github.com>:
