### ISSUE TITLE
Two more features?

### ISSUE THREAD

**Issue by Amarok73** [joeyjojojunior/simFFB#3]
First of all, big thank You for taking care about this software and doing effort to make it even more usefull! As the G940 user, i really appreciate what You do with it. 

And regarding some other features that could be helpfull, would it be possible to put somewhere in program window indicator, what mode he's in, 1 or 2? This would be mostly for troubleshooting the force feedback issues. If everything is ok, then the mode is rather easily recognizable due to rather big differences between those two settings.

Then second request is actually something that is in my mind from very beginning. 
It is that if it could be possible to add hotkey setting for switching the trim type between none->insta->progressive->both->back to none, and also indicator which type is currently enabled?

**Comment by joeyjojojunior** [comment]
This shouldn't be too difficult. I'll work on it.

**Comment by Amarok73** [comment]
Could it be, that the window position will be saved at application close, then restored on next open? I am usualy moving it to the second screen.

**Comment by joeyjojojunior** [comment]
Ok, I implemented these changes. I moved the trim type selection to radio buttons in the main window. That way it's easy to see which is selected, especially when you cycle with the hotkey. For spring force 1/2 indication, I just put an asterisk beside the label for whichever one is active. I don't want to put it up as a release until it's tested a bit more, but you can download it here if you want to try it:

http://s000.tinyupload.com/?file_id=02215825954543475311

Let me know how it is/if you find any bugs.

**Comment by Amarok73** [comment]
Here are my findings:
1. Sometimes it happens that RightWindowsKey is actually bound to the context menu key, the one to the right from right Windows key. But this one happens erraticaly. 
2. Control and Shift keys doesn't seems to be recognized, but for me it's not big deal.
3. I can't regcognize the tilda key(the one to the left from key 1) on the list
4. Switching between trim modes happens very quickly in continous loop so it's qute hard to release key when needed mode is selected. 
5. ~~I don't know if this is my joystick's model property, but sometimes, in the Hold mode, the application starts working so, when button is pressed, the application doesn't release forces, and after the hold button is released the new force center point is applied. 
After the indicatior You've implemented @joeyjojojunior, I can see, that hold button, when pressed switches the mode to second one, and keeps it enabled as long as the button is pressed, so I zeroed all forces in second mode, but force restistance is significant. 
After the application restart it sometimes returns to the normal/expected behavior, but not always. Sometimes it's needed to restart application couple times, or - as I keep all previous versions - sometimes it helps to start and stop the average_pilot, or Jazzerman versions of application.~~
Disregard above for now. It can be that it was caused by non-instant-or-both mode enabled, so It need more testing.

EDIT:
6. Labels for Sppring, Damper and Friction forces, for both modes seems to be blinking, so as I assume it means' they're refreshed constantly in the loop, not when event related to them are triggered. A bit annoying feature. :-)

**Comment by joeyjojojunior** [comment]
(1)/(2) This is a bug someone else pointed out recently. Has to do with the wrong keymap codes set. I never used those bindings so I didn't realize. Should be an easy fix.
(3) Ok, I've added the back quote character to the key list. Tilde is Shift+backquote. I'm working on implementing modifiers so you can use Shift+backquote if you like.
(4) Hmm, do you expect it to be held down so it cycles through them at a certain speed? I tested it by just tapping the key each time I wanted to cycle to the next one, and it works well that way. Do you get different behavior?
(6) Strange, does not flicker for me. Is your OS UI scale set to something other than 1? 

I do it in the main loop, yes. I tried a more efficient way of doing it that should hopefully help, but I can't avoid checking for something in the main loop because that's how the button states are polled. Previously I was loading the whole options struct at each iteration of the main loop which wasn't the best idea. Now I just check the state of a single global variable. Not sure if it will make a difference. 

Can you try it out? Run it in a fresh directory with no opt.dat file, because the options format has changed a bit. 
http://s000.tinyupload.com/?file_id=01567991329530448606

**Comment by Amarok73** [comment]
(1)/(2) - Ok.
(3) - Great to "hear" it! 
(4) - Not at any speed, just each keypress, regardless of the length of press, should change to next trim mode. In Visual Basic, there was event OnKeyRelease (as far as I remember), so keypress did nothing (as this event was not programmed), but when key with specific scancode have been released, the event was triggered. Of course, in this way, the change will not occur until key will be not released. Other way to get the effect I am thinking about is, there could be boolean flag set when key is detected, within if - endif clause that would check for the flag if is not set, then in key release event this variable would be reset to false. In this way, the mode would be changed as soon as key is pressed, but only one change will occur per key press.
(6) - The flickering is nothing regular. In current version I can't see it so far.

**Comment by AstonMartinDBS** [comment]
I'm surprised about the new features of the current v3.3 RC2, they improve the useability of simFFB further and make it much more intuitive. And I'm glad that you've added SW-FFB2-Icons!!! :)
Thank you for your refinements!
PS: I've noticed, that there are **two** identically icons in the .exe-file.

**Comment by AstonMartinDBS** [comment]
v3.3 RC2 runs very well with my UH-1H Huey in the mode "instant"! 
But there is a little issue: It's necessary to restart the application after changing certain values (esp. "damper force 2" or "friction force 2"), otherwise the stick jitters permanently after re-initialisation dinput.

**Comment by joeyjojojunior** [comment]
Does it only happen at high values of damper/friction?

**Comment by AstonMartinDBS** [comment]
AFAIR I've set damper2/friction2 at least to 25 % for testing purposes.

**Comment by joeyjojojunior** [comment]
Hmm, okay. If it happens again, please note the exact damper/friction settings to help me test. And you are using MS FFB2, correct? Work has been really crazy lately so I haven't had much energy to work on SimFFB, but hopefully I'll have some time this weekend.

**Comment by AstonMartinDBS** [comment]
Correct, I'm using the MS SW FFB2. Hm... I could not repruduce the same behaviour as described above, but re-initialisation dinput after changing some values (in my case "damper force 2" and "friction force 2" to 50 %) caused another strange behaviour after pressing the TOGGLE button on the SW FFB2 (stick tends to go to center position). These were my settings (v3.3 RC2):
<img width="344" alt="20200502_simFFB_Settings" src="https://user-images.githubusercontent.com/52347451/80872977-b2812a00-8cb5-11ea-918e-16cdae34581c.PNG">
Quit & restart of simFFB fixed the issue.

**Comment by joeyjojojunior** [comment]
Forgot to ask, do you ever notice this happens when loading a new mission or something? I know sometimes the game can try to grab back input when that happens and requires reinitializing to get things working again.

**Comment by AstonMartinDBS** [comment]
Usually I start simFFB first and then DCS. While running DCS (after starting a mission) I use the hotkey for re-init dinput, what worked perfectly with v3.3 RC2.
Thx btw for expanding the hotkey-capabilities for re-initialisation dinput! :)

**Comment by AstonMartinDBS** [comment]
I've created a set of additional icons. If you wish, you can add them to your .exe for the Logitech G940 fans ;)
[Logitech-G940-Icons.zip](https://github.com/joeyjojojunior/simFFB/files/4571691/Logitech-G940-Icons.zip)
