### ISSUE TITLE
Force tension while in instant trim.

### ISSUE THREAD

**Issue by Amarok73** [joeyjojojunior/simFFB#4]
Ok,

So there is the issue with instant trim. 
![image](https://user-images.githubusercontent.com/6810260/81012923-a387ac80-8e5a-11ea-91f0-64f9a5890d43.png)
Above are the settings I am using. Only Hold button is mapped to true existing button on my joystick.
When I'll press the Hold button the star marked in red on the screenshot changes position to Spring Force 2, but no change of tension is applied, then when I'll release Hold button, immediately new force center is set and noticeable on the stick.
Now, if the Spring Force 2 is set to zero, this is scenario as described above, but when it is changed to value different from zero, then it seems, that this setting is reflected by the forces accordingly.
This happens both, when game is played (DCS, Falcon4 BMS, Elite Dangerous), as well as when I am just in the desktop, no game running, and Logitech profiler is shut down.

**Comment by joeyjojojunior** [comment]
Hmm, did it work before with an older version? And you were always using G940, right? I cleaned up some of the force code recently. Can you test with this version please: http://s000.tinyupload.com/?file_id=38077323648017648257

If I understand the issue correctly, this only happens with Spring Force 2 = 0? If you set Spring Force 2 to anything else, it works correctly?

**Comment by AstonMartinDBS** [comment]
It seems that this issue https://github.com/joeyjojojunior/simFFB/issues/3#issuecomment-622997909 doesn't occur in RC3 :)

**Comment by Amarok73** [comment]
Yes' I use G940, and this problem still exist in this version from the link. 
The Spring Force 2 must be set to non-zero value for Instant Trim to work properly, otherwise, when holding trim button, it changes nothing, but release of the button cause immediate change of centering force position.
Besides, what should be size of executable file? All previous versions are below 100 kbytes, but current one is around 350 kbytes large...
![image](https://user-images.githubusercontent.com/6810260/81508057-eede0700-9301-11ea-8b6b-7fd70b1553b2.png)

**Comment by joeyjojojunior** [comment]
Yes same size for me. I think it's because I added a Logitech G940 icon as well. Both icons are about 150kb. If you create a shortcut, you can select the icon you want to use. 

edit: By the way you didn't answer if this happened with an older version?

**Comment by joeyjojojunior** [comment]
@AstonMartinDBS: excellent!

**Comment by joeyjojojunior** [comment]
Ok, I think I found the cause. An older version of the app had a function called NoSpring() to handle the case where spring force = 0. I deleted it eventually because it didn't seem to be necessary. Looking through that commit I see:

> //nospring changes spring tension to a very low value so it feels as not tension is being applied.
> //Initialy it was just a function that called effect->stop, but it was troublesome, specially with the
> //**logitech g940**

Oops. I've restored the code that does this so hopefully it will fix the issue. 

Some other new things in this version:
  * Hotkeys now trigger on key release to prevent looping behavior
  * Titlebar icon will now reflect which joystick you have connected (FFB2 or G940)

So can you please test that this issue is fixed, and also let me know if you see the G940 icon in the titlebar when you load the app. 

http://s000.tinyupload.com/?file_id=00074713359896731011

edit: I just tried compiling it without the icons and I get 40kb filesize. So that's what it is.

**Comment by AstonMartinDBS** [comment]
>     * Titlebar icon will now reflect which joystick you have connected (FFB2 or G940)
Nice gimmick!

Let me know if there is a need for other FFB-Stick icons!

**Comment by joeyjojojunior** [comment]
Originally I was trying to find a way to make the titlebar icon the same as the shortcut icon but there wasn't an easy way to do that. So I found this workaround which I think is cooler :)

Not sure who else would use this app. Only other FFB stick I think anyone uses is Brunner, and they probably will use their own app for that. Did you make the icons yourself? Great work on them.

**Comment by AstonMartinDBS** [comment]
> Originally I was trying to find a way to make the titlebar icon the same as the shortcut icon but there wasn't an easy way to do that. So I found this workaround which I think is cooler :)

Yeah, this option is much smarter.

> Not sure who else would use this app. Only other FFB stick I think anyone uses is Brunner, and they probably will use their own app for that. Did you make the icons yourself? Great work on them.

I just extracted the joystick-pics from public sources and converted them into an .ico file. Thx for including them directly into your .exe!

**Comment by AstonMartinDBS** [comment]
There's a little issue in the RC4: the hotkey for re-init dinput (in my case: ctrl+subtract) only works, when simFFB has focus. Directly out from DCS the hotkey doesn't work.

**Comment by joeyjojojunior** [comment]
Argh, yeah that makes sense. I decided to treat both hotkeys the same, and capture them with window messages which only works when it is in focus. Forgot that people need to reinit when in the game. Hmm, this also means you won't be able to switch trim modes in game with the hotkey. Probably not great. I was hoping to avoid having to manually keep track of button release and stuff like that. The function for getting key state at any moment is very low level. Just gives you whether it is pressed or not at that exact moment. I'll have to come up with a better solution.

**Comment by Amarok73** [comment]
Works like a charm!

I didn't noticed problems with the hotkeys, can it be because I am usualy playing on borderless windows, and DCS in windowed mode?

**Comment by joeyjojojunior** [comment]
Awesome!!!

Yes, probably. With other applications, not having focus prevents the hotkeys from working. For example, if you open simFFB, then open a browser window and focus on it, the hotkey won't work anymore. I already found an alternate solution that works well. I think all that's left for the existing requests is to make the hotkey modifiers work.

**Comment by joeyjojojunior** [comment]
Oh, btw, did you get the G940 icon in the titlebar?

**Comment by Amarok73** [comment]
Yes, the icon is there.
And about hotkeys, I am using two monitors, and the SimFFB is always on the second screen, so it may also be the reason why it always works for me. I'll try to test it later today.

**Comment by AstonMartinDBS** [comment]
btw: the hotkey doesn't work when simFFB has lost it's focus to the desktop as well.

**Comment by Amarok73** [comment]
I confirm, the current version have this problem with hotkeys even when focus changed from application to the desktop. Previous version doesn't seems to behave this way.

**Comment by AstonMartinDBS** [comment]
Exactly. RC3 works best for me. The hotkey makes no sense, if we have to make a focus to the simFFB-window first.

**Comment by joeyjojojunior** [comment]
I think I fixed it:
http://s000.tinyupload.com/?file_id=06281617935028663150

It works like RC3, only I manually keep track of whether the button is down or released to prevent it cycling.

**Comment by AstonMartinDBS** [comment]
Yeah, it works again! Thank you for the quick fix!

**Comment by joeyjojojunior** [comment]
Sweet! I just need to get the modifier keys working and if there are no big bugs I can put it up as a release.

**Comment by Amarok73** [comment]
I can also confirm, now the keys are working regardless of the focus.

**Comment by joeyjojojunior** [comment]
OK, modifiers work now. You can enable them in the options menu. If no major issues after a week or so, I'll publish it as a release. Tinyupload doesn't seem to be working right now so I used a different host:

https://www34.zippyshare.com/v/PPoC4jTR/file.html

**Comment by AstonMartinDBS** [comment]
Great, modifiers work and there are no issues so far with my FFB2.

**Comment by Amarok73** [comment]
Same here, with my G940.
