### ISSUE TITLE
Noob question regarding compiling simFFB

### ISSUE THREAD

**Issue by MiGhooked** [joeyjojojunior/simFFB#6]
Hello joeyjojojunior,

I am a DCS user and no nothing about C++ coding or coding in general. Since I am using a G940, I wanted to try your simFFB build. So I installed Visual Studio 2019 as suggested. But the term "and hit build" is a bit to vague for me. The matter that I installed VS2019 in german language doesn't help either.

I see a window where I can set options to Debug, JIB Version, JIB Version 64, JIB Version debug, Release as well as configuration manager. To its right side another window with option Win32, x64 and again configuration manager. If I got it right, I may set this option before i build simffb. So if I set it to Release x64, VS will compile 64bit program?

Greetings,

Mig hooked

**Comment by joeyjojojunior** [comment]
Hello MiGhooked,

Yes if you select Release and x64 as below:
![](https://i.imgur.com/fmWgmb7.png)

Then go to Build->Build Solution and it should create a x64 exe in simFFB/x64/Release. 
![](https://i.imgur.com/i388aIH.png)

**Comment by MiGhooked** [comment]
Thx for the explaination. I gave it a try, but since during the compiling a possible data lose was recorded, I instead compiled it in Win32 and it works just fine.

**Comment by ThreeDeeJay** [comment]
By the way I just submitted https://github.com/joeyjojojunior/simFFB/pull/11 👀
